<?
    // Set page title.
    $this->headTitle($this->translate('Print Favorites'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li><a href="' .$this->url('cart-home'). '">' .$this->transEsc('Cart'). '</a></li> '
    . '<li class="active">' . $this->transEsc('Export Favorites') . '</li>';
    
    if ($this->auth()->isLoggedIn()) {
        $selectAction = 'Lightbox.close();return false;';
    } else {
        $selectAction = 'Lightbox.get(\'Cart\',\'Cart\');return false;';
    }
?>
<h2><?=$this->transEsc('Print Favorites')?></h2>

<?=$this->flashmessages()?>

<form class="form-horizontal" method="post" action="<?=$this->url('cart-myresearchbulk')?>" name="doExportForm" title="<?=$this->transEsc('Print Items')?>">  
  <?=$this->translate('no_items_selected'); ?>
  <ul>
    <li>     
      <?=$this->translate('no_items_selected_option_select')?>
    </li>
    <li>
      <?=$this->translate('no_items_selected_option_process_list')?>
    </li>
  </ul>
  <br />
  <input type="hidden" name="allFromList" value="<?=$this->allFromList?>" />
  <input class="btn btn-default" type="submit" onclick="<?=$selectAction ?>" value="<?=$this->transEsc('Select Items')?>"/>
  <input class="btn btn-default" type="submit" name="doExport" value="<?=$this->transEsc('Process List')?>" data-lightbox-ignore/>
</form>