<?
  // Set page title.
  $this->headTitle($this->translate('Articles & more'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'RDSProxy';
  }
  
  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
?>

<div>

	<? $this->layout()->navigation = $this->render('layout/navigation.phtml');?>
  <?=$this->layout()->navigation ?>


	<div class="rds_info">

	</div>

	<div class="rds_content">
    Die Literatursuchmaschine der Universität Hohenheim<br />
    Suchen Sie parallel in den Beständen der Hohenheimer Bibliotheken (Bücher & mehr) sowie in weiteren Literaturnachweisen (Artikel & mehr).<br /> 
    Zugriff auf lizenzierte E-Medien erhalten Sie im Universitätsnetz. Angehörige der Universität haben nach Login auch Vollzugriff auf den Bereich "Artikel & mehr".
	</div>


</div>