<?
  // Set page title.
  $this->headTitle($this->translate('Articles & more'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'RDSProxy';
  }
  
  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('RDSProxy') . '</li>';
?>

<div>

	<? $this->layout()->navigation = $this->render('layout/navigation.phtml');?>
  <?=$this->layout()->navigation ?>

	<div class="rds_info">
		<?=$this->transEsc("RDS_HOME_INFO_" . $this->searchClassId);?>
	</div>

</div>