<ul>

	<li>
		<a href="http://ub.con-version.com/meta-navigation/chat/" data-menu-uid="4271" data-ajax-request="http://ub.con-version.com/meta-navigation/chat/rawcontent/">
			Chat
		</a>
	</li>

	<li>
		<a href="http://ub.con-version.com/meta-navigation/ausleihkonto/" data-menu-uid="4272" data-ajax-request="http://ub.con-version.com/meta-navigation/ausleihkonto/rawcontent/">
			Ausleihkonto
		</a>
	</li>

	<li>
		<a href="http://ub.con-version.com/meta-navigation/fachportale/" data-menu-uid="4270" data-ajax-request="http://ub.con-version.com/meta-navigation/fachportale/rawcontent/">
			Fachportale
		</a>
	</li>

</ul>