<ul>
  <li>
    <a href="https://www-dev.ub.uni-freiburg.de/meta-navigation/chat/" data-menu-uid="4271" data-ajax-request="https://www-dev.ub.uni-freiburg.de/meta-navigation/chat/rawcontent/">
      Chat
    </a>
  </li>
  <li>
    <a href="https://www-dev.ub.uni-freiburg.de/meta-navigation/ausleihkonto/" data-menu-uid="4272" data-ajax-request="https://www-dev.ub.uni-freiburg.de/meta-navigation/ausleihkonto/rawcontent/">
      Ausleihkonto
    </a>
  </li>
  <li>
    <a href="https://www-dev.ub.uni-freiburg.de/meta-navigation/fachportale/" data-menu-uid="4270" data-ajax-request="https://www-dev.ub.uni-freiburg.de/meta-navigation/fachportale/rawcontent/">
      Fachportale
    </a>
  </li>
</ul>