<?
	// Set up the search box -- there are three possible cases:
  $this->layout()->searchbox = $this->render('search/searchbox.phtml');
  $this->searchType = $this->params->getSearchType();
?>

<nav class="nav searchbox hidden-print">
	<? $this->layout()->navigation = $this->render('layout/navigation.phtml');?>
  <?=$this->layout()->navigation ?>
</nav>

<?
  // Load standard settings from the default search results screen:
  echo $this->render('search/results.phtml');
?>