<?
  // Set page title.
  $this->headTitle($this->translate('Search History'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('History') . '</li>';
  $this->searchParams();
  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }
  
?>

<div class="row">

	<? $this->layout()->navigation = $this->render('layout/navigation.phtml');?>
  <?=$this->layout()->navigation ?>

  <div class="<?=$this->layoutClass('mainbody')?>">
    <? if (!empty($this->saved)): ?>
      <h2><?=$this->transEsc("history_saved_searches")?></h2>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => true));?>
    <? endif; ?>

    <h2><?=$this->transEsc("history_recent_searches")?></h2>
    <? if (!empty($this->unsaved)): ?>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => false));?>
      <a href="?purge=true"><i class="fa fa-remove"></i> <?=$this->transEsc("history_purge")?></a>
    <? else: ?>
      <?=$this->transEsc("history_no_searches")?>
    <? endif; ?>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext(
        "myresearch/menu.phtml",
        // Only activate search history in account menu if user is logged in.
        $this->auth()->isLoggedIn() ? array('active' => 'history') : array()
      );
    ?>
  </div>
</div>