<? if ($this->pageCount): ?>
  <div class="ui-pagination">
    <? if (isset($this->previous)): ?>
      <ul class="controls">
        <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage(1)?>"><span><i class="icon icon-ubfr-pointer-start"></i></span></a></li>
        <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>"><span><i class="icon icon-ubfr-pointer-prev"></i></span></a></li>
      </ul>
    <? else: ?>
      <ul class="controls disabled">
        <li><span><i class="icon icon-ubfr-pointer-start"></i></span></li>
        <li><span><i class="icon icon-ubfr-pointer-prev"></i></span></li>
      </ul>
    <? endif; ?>
    <? if (count($this->pagesInRange) > 1): ?>
      <ul class="pages">
        <? foreach ($this->pagesInRange as $page): ?>
          <? if ($page != $this->current): ?>
            <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($page)?>"><?=$page?></a></li>
          <? else: ?>
            <li class="active"><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($page)?>"><?=$page?></a></li>
          <? endif; ?>
        <? endforeach; ?>
      </ul>
    <? endif; ?>
    <? if (isset($this->next)): ?>
      <ul class="controls">
        <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><span class="icon icon-ubfr-pointer-next"></span></a></li>
        <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->pageCount)?>"><span class="icon icon-ubfr-pointer-end"></span></a></li>
      </ul>
    <? else: ?>
      <ul class="controls disabled">
        <li><span class="icon icon-ubfr-pointer-next"></span></li>
        <li><span class="icon icon-ubfr-pointer-end"></span></li>
      </ul>
    <? endif; ?>
  </div>
<? endif; ?>