<?
  if (isset($this->renderSearchbox) && $this->renderSearchbox == false) {
    $this->layout()->searchbox = "";
  } else {
    $this->layout()->searchbox = $this->render('search/searchbox.phtml');
  }
  
?>

<div style="border: 0px solid red;">

  <div class="rds_title"><?=$this->transEsc('RDS_CATALOG_TITLE')?></div>

  <div class="rds_searchbox">
    <nav class="nav searchbox">
      <?=$this->layout()->searchbox ?>
    </nav>
  </div>

  <div class="rds_searchTabs">
      <?= $this->render('search/searchTabs'); ?>
  </div>

   <div class="rds_subnav">
        <ul>
            <li><a href="<?=$this->url('home') ?>Feedback"><?=$this->transEsc('RDS_FEEDBACK')?></a></li>
            <li><a href="<?=$this->url('home') ?>Help"><?=$this->transEsc('RDS_HELP')?></a></li>
        </ul>        
    </div>
  
  
</div>