<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <style>
        th {
            width: 180px;
            text-align:left;
            vertical-align: top;
        }
        
        td {
            width: 500px;
        }
        .title {
            border-bottom: 1px solid lightgray;
        }
        @media print {
    body, table {
        font: 12px arial, sans-serif;
    }

  #printBtn {
    display:none;
  }
}
    </style>
  </head>
  <body>
    <input id="printBtn" type="button" onclick="window.print();"value="<?=$this->transEsc("RDS_PRINT_PAGE") ?>">
    <br />
    
    <? 
      if (count($records) <= 1 ) {
        $header = count($records) . ' ' . $this->transEsc('RDS_ENTRY') . ' ' . $this->transEsc('RDS_PRINTED_ON') . ' ' . date("Y-m-d H:i:s");
      } else {
        $header = $this->transEsc('RDS_FAVORITE_LIST');
        $header .= '<br />';
        $header .= count($records) . ' ' . $this->transEsc('RDS_ENTRIES') . ' ' . $this->transEsc('RDS_PRINTED_ON') . ' ' . date("Y-m-d H:i:s");
      }
    ?>
    
    <?=$header ?>
    
    <hr />
    
    <? foreach ($records as $record): ?>
      <?=$record ?>
    <? endforeach; ?>
  </body>
</html>