   <!-- footer -->
        <div class="row footer-site__row-1">
          <div class="col-sm-8 footer-site__col footer-site__col-1"> 
            
            <!-- site search -->
            <div class="site-search">
              <form class="form-inline" role="form" action="/77679" method="get" name="solrsearch">
                <div class="site-search__col-1">
                  <label for="searchword" class="sr-only">Suche</label>
                  <input id="searchword" name="tx_solr[q]" class="form-control site-search__form-search" placeholder="Suchbegriff, Name, Studiengang …" type="text">
                </div>
                <div class="site-search__col-2">
                  <button type="submit" class="btn btn-primary site-search__form-submit"> <span>Suchen</span><i></i></button>
                </div>
              </form>
            </div>
            <!-- /site-search --> 
            
          </div>
          <!-- /col -->
          <div class="col-sm-4 footer-site__col footer-site__col-2"> 
            
            <!-- sharing -->
            <div class="sharing">
              <div class="sharing__wrp"> <span class="sharing__text">Begleiten Sie uns:</span> <a href="https://twitter.com/UniHohenheim" target="_top" class="sharing__item sharing__item-twitter" title="Auf Twitter teilen"><span>Twitter</span><i></i></a><a href="https://www.facebook.com/UniHohenheim" target="_top" class="sharing__item sharing__item-facebook" title="Auf Facebook teilen"><span>Facebook</span><i></i></a> </div>
            </div>
            <!-- /sharing --> 
            
          </div>
          <!-- /col --> 
        </div>
        <!-- /row -->
        
        <div class="row footer-site__row-2">
          <div class="col-sm-4 footer-site__col footer-site__col-1"> 
            <!-- navigation -->
            <nav class="footer-site__navigation">
              <ul>
                <li><a href="https://hohsearch-info.uni-hohenheim.de/impressum?&amp;N=1"  class="link">Impressum</a></li>
              </ul>
            </nav>
            <!-- /navigation -->
            <div class="lastchanged">&nbsp;Letzte Aktualisierung:&nbsp;07.10.2014&nbsp;|&nbsp;<a href="mailto:HohSearch?subject=Seite%20kommentieren:%20Systematische%20Suche&amp;body=Direktlink:%20http:%2F%2Fhohsearch-info.uni-hohenheim.de%2F103790%3F%26N%3D1">Feedback</a></div>
          </div>
          <!-- /col -->
          <div class="col-sm-4 footer-site__col footer-site__col-2"> 
            
            <!-- corporate -->
            <div class="footer-site__corporate">
              <div class="footer-site__corporate-content"> </div>
            </div>
            <!-- corporate --> 
            
          </div>
          <!-- /col -->
          <div class="col-sm-4 footer-site__col footer-site__col-3"> 
            
            <!-- contact -->
            <div class="footer-site__contact">
              <h4>Universität Hohenheim</h4>
              <p>Schloss Hohenheim 1, 70599 Stuttgart</p>
              <h4>Zentrale</h4>
              <p>Tel. 0711 459-0<br>
                Fax 0711 459-23960<br>
                <a href="mailto:post@uni-hohenheim.de">post@uni-hohenheim.de</a> </p>
              <h4>Studienberatung</h4>
              <p>Tel. 0711 459-22064<br>
                <a href="mailto:zsb@uni-hohenheim.de">zsb@uni-hohenheim.de</a></p>
            </div>
            <!-- /contact --> 
            
          </div>
          <!-- /col --> 
          
        </div>
        <!-- /row --> 
